version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # React
    depends_on:
      - backend 
    networks:
      - app-network
      

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1337:1337" # Strapi
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: ./data.db
    platform: linux/amd64
    volumes:
      - ./backend/data:/usr/src/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
