name: CI - Backend and Frontend Docker Testing

on:
  push:
    branches:
      - '*'

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # Build Docker Compose services
      - name: Build and start services
        run: docker-compose up --build -d

      # Run tests
      - name: Run frontend tests
        run: |
          docker-compose exec frontend npm test

      - name: Run backend tests
        run: |
          docker-compose exec backend npm test

      # Stop Docker Compose services
      - name: Stop services
        if: always()
        run: docker-compose down